// Copyright (c) 2026, Minghua Shen.
//
// Backward (FAGGeneral) kernel dispatch, split across per-(dtype, layout)
// translation units under autogen/ (generated by autogen/generate_kernels.py)
// so the 64 FAGGeneral instantiations
// (dtype x mask x deterministic x headdim x layout) compile in parallel: 16 per
// (dtype, layout) TU. flash_api.cpp computes all host-side setup (tiling,
// workspace, layout) and hands the raw device pointers / scalars to
// launch_bwd<kInputLayout>(); it picks dtype at runtime and layout at the call
// site (compile time).
//
// head_dim is NOT a generation axis: it is a runtime switch() over
// qk_headdim_kernel inside bwd_dispatch_run (see bwd_dispatch_common.hpp). The
// compile-time axes are dtype and kInputLayout only.
//
// This header stays lightweight (no CATLASS / kernel includes) so flash_api.cpp
// can include it without dragging in the heavy kernel templates.

#pragma once

#include <cstdint>
#include "acl/acl.h"

struct BwdLaunchArgs {
    uint32_t blockDim;
    aclrtStream aclStream;
    uint64_t fftsAddr;
    bool is_bf16;
    bool has_attn_mask;
    bool deterministic;
    uint32_t qk_headdim_kernel;  // 64 / 128 / 192 / 256
    uint8_t *dOutDevice;
    uint8_t *qDevice;
    uint8_t *kDevice;
    uint8_t *vDevice;
    uint8_t *outDevice;
    uint8_t *attenMaskDevice;    // may be nullptr when has_attn_mask is false
    uint8_t *softMaxLseDevice;
    uint8_t *cuSeqQlenDevice;    // may be nullptr in BSND mode
    uint8_t *cuSeqKvlenDevice;   // may be nullptr in BSND mode
    uint8_t *dqDevice;
    uint8_t *dkDevice;
    uint8_t *dvDevice;
    uint8_t *workspaceDevice;
    uint8_t *tilingDevice;
};

// Per-(dtype, layout) implementation, defined in
// autogen/bwd_dispatch_<dtype>_<layout>.cpp via bwd_dispatch_common.hpp. Each TU
// instantiates one bwd_dispatch_run<DType, kInputLayout> (16 FAGGeneral variants:
// mask x deterministic x headdim). kInputLayout is BSND (0) or TND (1) from
// kernel_common_fag.hpp.
template <typename DType, uint32_t kInputLayout>
void bwd_dispatch_run(const BwdLaunchArgs &a);

// Runtime entry: kInputLayout is fixed at the call site, then the matching
// dtype's launcher is selected. bwd_dispatch_run is explicitly instantiated per
// (dtype, kInputLayout) in the autogen TUs.
template <uint32_t kInputLayout>
inline void launch_bwd(const BwdLaunchArgs &a) {
    if (a.is_bf16) {
        bwd_dispatch_run<bfloat16_t, kInputLayout>(a);
    } else {
        bwd_dispatch_run<half, kInputLayout>(a);
    }
}
