// Copyright (c) 2026, Minghua Shen.
//
// Forward (FAInfer) kernel dispatch, isolated into per-(dtype, layout)
// translation units under autogen/ (generated by autogen/generate_kernels.py)
// so the 20 SplitFuse::FAInfer template instantiations
// (2 dtype x {paged/non-paged with flash-decode variants} x {causal/no-mask}
// x {TND/BSND}) compile in parallel across cores. flash_api.cpp computes all
// host-side setup (tiling, workspace, layout, block-table/mask pointers) and
// hands the raw device pointers / scalars to launch_fwd<IS_TND>().
//
// head_dim is NOT a generation axis: the forward does not bin by head_dim (it
// is a runtime tiling value). The compile-time axes are dtype and IS_TND only.
//
// This header stays lightweight (no CATLASS / kernel includes) so flash_api.cpp
// can include it without dragging in the heavy kernel templates.

#pragma once

#include <cstdint>
#include "acl/acl.h"

struct FwdLaunchArgs {
    uint32_t launchBlockDim;
    aclrtStream aclStream;
    uint64_t fftsAddr;
    bool is_bf16;
    bool paged_KV;
    bool is_causal;
    bool flashDecodeFlag;
    uint8_t *qDevice;
    uint8_t *kDevice;
    uint8_t *vDevice;
    uint8_t *maskDevice;          // may be nullptr when is_causal is false
    uint8_t *blockTableDevice;    // may be nullptr when paged_KV is false
    uint8_t *oDevice;
    uint8_t *softmaxLseDevice;
    uint8_t *qSeqDevice;
    uint8_t *kvSeqDevice;
    uint8_t *workspaceDevice;
    uint8_t *tilingDevice;
};

// Per-(dtype, layout) implementation, defined in autogen/fwd_dispatch_<dtype>_<layout>.cpp
// via fwd_dispatch_impl.hpp. Each TU instantiates one launch_fwd_dtype<DType, IS_TND>.
template <typename DType, bool IS_TND>
void launch_fwd_dtype(const FwdLaunchArgs &a);

// Runtime entry: IS_TND (false => BSND, true => TND) is fixed at the call site,
// then the matching dtype's launcher is selected. launch_fwd_dtype is explicitly
// instantiated per (dtype, IS_TND) in the autogen TUs.
template <bool IS_TND>
inline void launch_fwd(const FwdLaunchArgs &a) {
    if (a.is_bf16) {
        launch_fwd_dtype<bfloat16_t, IS_TND>(a);
    } else {
        launch_fwd_dtype<half, IS_TND>(a);
    }
}
