// Copyright (c) 2026, Minghua Shen.
//
// FAGGeneral (FlashAttentionGrad) backward kernel dispatch for v2, isolated
// from fag_general_host.cpp into per-(dtype, layout) translation units under
// autogen/ (generated by autogen/generate_kernels.py) so the 64 FAGGeneral
// instantiations (dtype x causal x deterministic x headdim x layout) compile
// in parallel: 16 per (dtype, layout) TU.
//
// fag_general_host.cpp computes all host-side setup (tiling, workspace, layout)
// and hands the raw device pointers / scalars to
// launch_fag_general_dispatch<kInputLayout>(); the dispatch selects dtype and
// launches the matching ::FAGGeneral<...>. kInputLayout is chosen at the call
// site (varlen => TND, non-varlen => BSND) and is a compile-time constant, so
// only the two layouts actually used are instantiated.
//
// This header stays lightweight (no CATLASS / kernel includes) so
// fag_general_host.cpp can include it without dragging in the heavy kernel
// templates.

#pragma once

#include <cstdint>
#include "acl/acl.h"

struct FagGeneralLaunchArgs {
    uint32_t blockDim;
    aclrtStream aclStream;
    uint64_t fftsAddr;
    bool is_causal;
    bool deterministic;
    uint32_t qk_headdim_kernel;   // 64 / 128 / 192 / 256
    uint8_t *dOutDevice;
    uint8_t *qDevice;
    uint8_t *kDevice;
    uint8_t *vDevice;
    uint8_t *outDevice;
    uint8_t *attenMaskDevice;     // may be nullptr when is_causal is false
    uint8_t *softMaxLseDevice;
    uint8_t *cuSeqQlenDevice;
    uint8_t *cuSeqKvlenDevice;
    uint8_t *dqDevice;
    uint8_t *dkDevice;
    uint8_t *dvDevice;
    uint8_t *workspaceDevice;
    uint8_t *tilingDevice;
};

// Per-(dtype, layout) implementation, defined in
// autogen/fag_general_dispatch_<dtype>_<layout>.cpp. Each TU instantiates only
// its dtype's FAGGeneral variants for the requested layout (causal x
// deterministic x headdim => 16 per layout). Defined via fag_general_dispatch_impl.hpp.
template <uint32_t kInputLayout>
void launch_fag_general_dispatch_bf16(const FagGeneralLaunchArgs &a);
template <uint32_t kInputLayout>
void launch_fag_general_dispatch_fp16(const FagGeneralLaunchArgs &a);

// Runtime entry: pick dtype, dispatch to the matching dtype TU. kInputLayout
// (TND / BSND) is fixed at the call site.
template <uint32_t kInputLayout>
inline void launch_fag_general_dispatch(bool is_bf16, const FagGeneralLaunchArgs &a) {
    if (is_bf16) {
        launch_fag_general_dispatch_bf16<kInputLayout>(a);
    } else {
        launch_fag_general_dispatch_fp16<kInputLayout>(a);
    }
}
